drop table if exists carrier, point, route, trip, ticket, users, users_roles;

create table if not exists carrier
(
    id      bigint generated by default as identity primary key,
    company varchar(50) not null,
    phone   varchar(11) not null,
    constraint uq_carrier_company unique (company),
    constraint uq_carrier_phone unique (phone)
);

create table if not exists point
(
    id    bigint generated by default as identity primary key,
    title varchar(50) not null,
    constraint uq_point unique (title)
);

create table if not exists route
(
    id                   bigint generated by default as identity primary key,
    route_number         varchar(10) not null,
    departure_point_id   bigint         not null,
    destination_point_id bigint         not null,
    carrier_id           int references carrier (id) on delete cascade,
    duration             interval
);

create table if not exists trip
(
    id        bigint generated by default as identity,
    title     varchar(10) not null,
    route_id  bigint references route (id) on delete cascade,
    date_time timestamp without time zone,
    price     int         not null,
    amount    int         not null,
    constraint pk_trip_id primary key (id),
    constraint uq_tirp_title unique (title)
);

create table if not exists users
(
    id        bigint generated by default as identity,
    login     varchar(20)  not null,
    password  varchar(100) not null,
    full_name varchar(100) not null,
    constraint pk_user_id primary key (id),
    constraint uq_user_login unique (login)
);

create table if not exists ticket
(
    id           bigint generated by default as identity,
    trip_id      bigint references trip (id) on delete cascade,
    user_id      bigint references users (id) on delete set null,
    place_number int not null,
    constraint pk_ticket_id primary key (id)
);

create table if not exists users_roles
(
    user_id bigint       not null,
    role    varchar(255) not null,
    constraint fk_uses_roles_users foreign key (user_id) references users (id) on delete cascade
);

create index carrier_company on carrier (company);
create index point_title on point (title);
create index trip_date on trip (date_time);