drop table if exists carrier, route, trip, ticket, users;

create table if not exists carrier
(
    id      int generated by default as identity primary key,
    company varchar(50) not null,
    phone   varchar(11) not null,
    constraint uq_carrier_company unique (company),
    constraint uq_carrier_phone unique (phone)
);

create table if not exists route
(
    id                int generated by default as identity primary key,
    route_number      varchar(10) not null,
    departure_point   varchar(50) not null,
    destination_point varchar(50) not null,
    carrier_id        int references carrier (id) on delete cascade,
    duration          interval
);

create table if not exists trip
(
    id        bigint generated by default as identity,
    title     varchar(10) not null,
    route_id  int references route (id) on delete cascade,
    date_time timestamp without time zone,
    price     int         not null,
    amount    int         not null,
    constraint pk_trip_id primary key (id),
    constraint uq_tirp_title unique (title)
);

create table if not exists users
(
    id        bigint generated by default as identity,
    login     varchar(20)  not null,
    password  varchar(100) not null,
    full_name varchar(100) not null,
    constraint pk_user_id primary key (id),
    constraint uq_user_login unique (login)
);

create table if not exists ticket
(
    id           bigint generated by default as identity,
    trip_id      int references trip (id) on delete cascade,
    user_id      int references users (id) on delete set null,
    place_number int not null,
    constraint pk_ticket_id primary key (id)
);