version: '3.1'
services:
  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - tickets-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tickets-db:5432/main-service-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  tickets-db:
    image: postgres:14-alpine
    container_name: tickets-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=main-service-db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"